sudo: required
language: java
jdk: oraclejdk8
node_js:
- 9.9.0
services:
- docker
install: true
env:
  local:
    maven:
    - repository=$HOME/.m2
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  chrome: stable
  sonarcloud:
    organization: processpuzzle
    token:
      secure: "$SONAR_TOKEN"
    branches:
    - development
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_cf7827a05a5b_key -iv $encrypted_cf7827a05a5b_iv -in codesigning.asc.enc -out codesigning.asc -d
- nvm install node
- nvm use node
- npm install -g npm@5.8.0
- if [ ${TRAVIS_BRANCH} == development ]; then DEPLOYMENT_ENVIRONMENT=dev; elif [
  -n ${TRAVIS_TAG} ]; then DEPLOYMENT_ENVIRONMENT=prod; else DEPLOYMENT_ENVIRONMENT=integ;
  fi; export DEPLOYMENT_ENVIRONMENT;
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  - "./processpuzzle-microservice-seed-ui/node_modules"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g typescript
- npm remove -g angular-cli
- npm uninstall -g @angular/cli
- npm cache clean --force
- npm install -g @angular/cli@latest
- npm install -g @angular/compiler-cli
- ng --version
- npm install --prefix ./processpuzzle-microservice-seed-ui
- npm update --prefix ./processpuzzle-microservice-seed-ui
script:
- mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar --settings travis-maven-settings.xml -B
deploy:
- provider: script
  skip_cleanup: true
  script: mvn deploy -Dmaven.test.skip=true --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
  on:
    branch: development
- provider: releases
  api_key:
    secure: XYnuZULC/Qol43bAWqH6nBzkYtjNnERQq+PppaYtcWaB9sbDJQXBj2MqLF355BFI6IA9FSsx1GLdX5R3+tAJsteWyq6Xrk7WpLDSPdOYhU3BlUCJeU35YQkZ+rPPsHfDzBghTOEH3OxqcmozlUVqvg1JyaZ2fitGBNRuGCPN6k/y7fd3jtOT6BhSPAMIKodr/B+RW+sGfjl+ffFFjFXNIOyBa7Y6LINlJdgr5mJGmVQPsUiJeuVx58nBxuzRbKoX9d/vMbeiLkuFRVqEzmcDptl1MrqcGuVwxPzuT9wCfGSMUN8X/hss74ZTbmeAZ6jjk8xo8QPlqAxr62ChkFeGKRsZhiHcLfc6J7G0+JfY+Wwx/ra3EwBz4kfdZ34HgHy1c83AfuT4zj+UByhr3EXf5Xi+UfT5BcwgvdRsZ6yFw0CtBjukC2Bc5zdrusQzmpEK+S4a8X0jdDpLsDj0oJjuoM1DVEp83TiFah9/4F3c5qYRXHRjkIF46XHivWPhJwYKpWKGo/nUpJCxX0MgCUb+r+RcuxALiARAJmj7ZdcTKNfuSpdxFR4IZjVlR40ASRWJJEMs9cOWIsIjrggVeScFB0quBL/Va2SsCar8+6JaSahQg2LKT9P5lVS6KUNoLu7E7xSkkKvrBApU3awNyd92WygmAA3mIzVCeBD+wW8TZF4=
  file:
  - processpuzzle-core-services/target/processpuzzle-core.zip
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: ZsZs/processpuzzle-core
