server:
  port: 9125
  contextPath: /

security:
  headers:
    cache: false

endpoints:
  shutdown:
    sensitive: false
    enabled: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      javax.persistence.schema-generation.scripts.create-target: target/schema.sql
      javax.persistence.schema-generation.scripts.action: create      
  h2:
    console:
      enabled: true
      path: /h2-console

storage:
  location: upload-files
    