server:
  port: 9125
  servlet:
    context-path: /

security:
  headers:
    cache: false

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /admin/actuator
      exposure:
        include: '*'

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:tcp://localhost/~/mortgage-service-test
    username: SA
    password: 
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  thymeleaf:
    prefix: classpath:/templates
    
logging:
  config: "classpath:logback-spring.xml"    